services:
    mqtt_broker:
        container_name: mqtt_broker
        image: mqtt_broker:0.1.0
        build:
            context: ./backend/
            dockerfile: ./mqtt_broker/Dockerfile.broker
        ports:
            - 1885:1885
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 100M
        depends_on:
            a_sbm_database_1:
                condition: service_healthy
    mqtt_pusher: 
        container_name: mqtt_pusher 
        image: mqtt_pusher:0.1.0
        build:
            context: ./backend/
            dockerfile: ./Dockerfile.pusher
        environment:
            RUST_LOG: TRACE 
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 100M
        depends_on:
            - mqtt_broker 
            - a_sbm_database_1 
    api_server:
        container_name: api_server
        image: api_server:0.1.0
        build:
            context: ./backend/
            dockerfile: ./Dockerfile.api
        environment:
            IS_DATABASE_CLUSTERED: 1 
        ports:
            - 4000:4000
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 4000M
        depends_on:
            a_sbm_database_1:
                condition: service_healthy
    a_sbm_database_1:
        container_name: sbm_database_1
        image: sbm_database:0.2.0
        build: 
            context: ./database/
            dockerfile: Dockerfile.database
        environment:
            IS_REPLICA: 0
            MONGODB_PORT: 27017
        ports:
            - 27017:27017
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/sbm_database --quiet
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 500M
    sbm_database_2:
        container_name: sbm_database_2 
        image: sbm_database:0.2.0
        build:
            context: ./database/
            dockerfile: ./Dockerfile.database
        environment:
            IS_REPLICA: 1
            MONGODB_PORT: 27018
        ports:
            - 27018:27018
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 500M 
    sbm_database_3:
        container_name: sbm_database_3 
        image: sbm_database:0.2.0
        build:
            context: ./database/
            dockerfile: ./Dockerfile.database
        environment: 
            IS_REPLICA: 1
            MONGODB_PORT: 27019
        ports:
            - 27019:27019
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 500M 
    alert_generator: 
        container_name: alert_generator 
        image: alert_generator:0.1.0
        build:
            context: ./backend/
            dockerfile: ./Dockerfile.alerter
        environment:
            RUST_LOG: TRACE 
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 100M
        depends_on:
            a_sbm_database_1:
                condition: service_healthy
