services:
    mqtt_broker:
        container_name: mqtt_broker
        image: mqtt_broker:0.1.0
        build:
            context: .
            dockerfile: ./backend/mqtt_broker/Dockerfile.broker
        ports:
            - 1885:1885
    database_primary:
        container_name: initial_primary
        image: sbm_database:0.2.0
        build: 
            context: ./database/
            dockerfile: Dockerfile.database
        environment:
            IS_REPLICA: 0
            MONGODB_PORT: 27017
        ports:
            - 27017:27017
    database_replica_1:
        container_name: replica_1
        image: sbm_database:0.2.0
        build:
            context: ./database/
            dockerfile: ./Dockerfile.database
        environment:
            IS_REPLICA: 1
            MONGODB_PORT: 27018
        ports:
            - 27018:27018
    database_replica_2:
        container_name: replica_2 
        image: sbm_database:0.2.0
        build:
            context: ./database/
            dockerfile: ./Dockerfile.database
        environment: 
            IS_REPLICA: 1
            MONGODB_PORT: 27019
        ports:
            - 27019:27019
