services:
    initial_primary:
        container_name: initial_primary
        image: sbm_database:0.2.0
        build:
            context: .
            dockerfile: Dockerfile.database
        environment:
            IS_REPLICA: 0
            MONGODB_PORT: 27017
        ports:
            - 27017:27017
    replica_1:
        container_name: replica_1
        image: sbm_database:0.2.0
        build:
            context: .
            dockerfile: Dockerfile.database
        environment:
            IS_REPLICA: 1
            MONGODB_PORT: 27018
        ports:
            - 27018:27018
    replica_2:
        container_name: replica_2 
        image: sbm_database:0.2.0
        build:
            context: .
            dockerfile: Dockerfile.database
        environment: 
            IS_REPLICA: 1
            MONGODB_PORT: 27019
        ports:
            - 27019:27019
