services:
    mqtt_broker:
        container_name: mqtt_broker
        image: mqtt_broker:0.1.0
        build:
            context: .
            dockerfile: Dockerfile.broker
        ports:
            - 1885:1885
    mqtt_auth:
        container_name: mqtt_auth
        image: mqtt_auth:0.1.0
        build: 
            context: .
            dockerfile: Dockerfile.auth
        ports:
            - 27017:27017
