name: Run Frontend Linting and Tests

on:
  pull_request:
    branches: ["main", "release/**"]
    paths: ["sbm-dashboard/**"]
  workflow_dispatch:

permissions:
  actions: write
  deployments: write
  packages: write
  pages: write
  id-token: write

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Lint, Build and Test
        run: |
          cd sbm-dashboard
          npm install
          npm run lint 
          # TODO: Add test command once (if?) tests setup.
          npm run build
