# obtained from https://stackoverflow.com/a/75414339
name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && !startsWith(github.head_ref, 'release/')
        run: |
          echo "ERROR: You can only merge into main from a release branch."
          exit 1
